spring:
  config:
    activate:
      on-profile: "dev"
  kafka:
    consumer:
      bootstrap-servers: 192.168.7.182:9092,192.168.7.183:9092,192.168.7.184:9092
      topics: dev-keti-finance
      group-id: dev-keti-finance-consumer-01
      auto-offset-reset: latest
      listener: 3
      enable-auto-commit: true
      poll-timeout: 1000
      auto-commit-interval-ms: 1000
      session-timeout-ms: 30000
      key-deserializer-class-config: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer-class-conifg: org.apache.kafka.common.serialization.StringDeserializer
  influxdb:
    url: http://192.168.100.46:8086
    database: keti
    username: admin
    password: qwer1234!@
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
    gzip: true
    
logging:
  path:
    dir: /applog/keti-launcher-finance
    file: keti-launcher-finance
  level:
    root: info