spring:
  config:
    activate:
      on-profile: "common"
  main:
    web-application-type: none
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  restTemplate:
    factory:
      readTimeout: 1000
      connectTimeout: 3000
    httpClient:
      maxConnTotal: 80
      maxConnPerRoute: 4
  collector:
    target: 50
    interval: 24
  weatherApi:
    end-point: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/
    end-point-service: getUltraSrtNcst
    end-point-service-key: nkrMhfspfYjvNTfgACykGqom2kLmq5zeNHa1VI1kDgT4xgZQ7M4UxQ5rub9RCQL%2BpvW0%2BQFDRncdJ5WLLUb4gA%3D%3D
    

info:
  app:
    name: keti-collector-weather
    version: 0.0.1-SNAPSHOT

---

spring:
  profiles:
    group:
      "local": "common,local"
      "wiz": "common,wiz"
      "dev": "common,dev"
      "prod": "common,prod"