spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/keti?reconnect=true&characterEncoding=UTF-8
    username: keti
    password: 'ketiabcs'
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      topic: dev-keti-weather
      acks: -1
      retries: 1
      batch-size: 16384
      linger-ms: 0
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
      buffer-memory: 33554432
      max-block-ms: 60000
      max-request-size: 125829120
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compresstion-type: lz4
  pid:
    file: /programdrive/WFcollector/keti-collector-weather/keti-collector-weather.pid

logging:
  path:
    dir: /programdrive/WFcollector/keti-collector-weather/applog
    file: keti-collector-weather
  level:
    root: info