spring:
  config:
    activate:
      on-profile: "prod"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      topics: dev-keti-weather
      group-id: dev-keti-weather-consumer-01
      auto-offset-reset: latest
      listener: 1
      enable-auto-commit: true
      poll-timeout: 1000
      auto-commit-interval-ms: 1000
      session-timeout-ms: 30000
      key-deserializer-class-config: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer-class-conifg: org.apache.kafka.common.serialization.StringDeserializer
  influxdb:
    url: http://localhost:8086
    database: keti_rtd
    username: clust
    password: clustketi
    retention-policy: autogen
    connect-timeout: 15
    read-timeout: 30
    write-timeout: 15
    gzip: true
  pid:
    file: /programdrive/WFcollector/keti-launcher-weather/keti-launcher-weather.pid
    
logging:
  path:
    dir: /programdrive/WFcollector/keti-launcher-weather/applog
    file: keti-launcher-weather
  level:
    root: info