spring:
  config:
    activate:
      on-profile: "prod"
  multipart:
    location: /programdrive/CsvServer/appdata/keti-collector-csv/
  influxdb:
    url: http://52.231.185.8:8087
    database: _internal
    username: clust
    password: clustketi
    retention-policy: autogen
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    gzip: true
  mongodb:
    url: mongodb://keti:clustketi@52.231.185.8:27170/?maxPoolSize=20&w=majority
  pid:
    file: /programdrive/WFcollector/keti-collector-csv/keti-collector-csv.pid
  # influx2: 
  #   url: http://192.168.100.46:8086 # URL to connect to InfluxDB.
  #   username: wizontech # Username to use in the basic auth.
  #   password: qwer1234!@ # Password to use in the basic auth.
  #   token: JfzQhp0bBEhshX9VyfvYrQwkgDbpPx75U2p4GnDZaE7-TqC_XPfZyzCukkMES2zQm3sZrXBXkJitBYKjf3sq0w== # Token to use for the authorization.
  #   org: wizontech # Default destination organization for writes and queries.
  #   bucket: keti # Default destination bucket for writes.
  #   logLevel: BASIC # The log level for logging the HTTP request and HTTP response. (Default: NONE) BODY
  #   readTimeout: 15s # Read timeout for OkHttpClient. (Default: 10s)
  #   writeTimeout: 15s # Write timeout for OkHttpClient. (Default: 10s)
  #   connectTimeout: 30s # Connection timeout for OkHttpClient. (Default: 10s)
    
logging:
  dir: /programdrive/CsvServer/applog/keti-collector-csv
  file: keti-collector-csv
  level:
    root: info