server:
  port: 8080
spring:
  servlet:
    context-path: /
    multipart:
      enabled: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
     prefix: classpath:/templates/
     check-template: true
     suffix: .html
     cache: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  config:
    activate:
      on-profile: "common"
  pid:
    file: ./keti-collector-csv.pid

info:
  app:
    name: keti-collector-csv
    version: 0.0.1-SNAPSHOT

---

spring:
  profiles:
    group:
      "local": "common,local"
      "wiz": "common,wiz"
      "dev": "common,dev"
      "prod": "common,prod"