spring:
  config:
    activate:
      on-profile: "common"
  main:
    web-application-type: none
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  restTemplate:
    factory:
      readTimeout: 1000
      connectTimeout: 3000
    httpClient:
      maxConnTotal: 80
      maxConnPerRoute: 4
  collector:
    target: 50
    interval: 24
  weatherApi:
    end-point: http://apis.data.go.kr/1360000/VilageFcstInfoService/
    end-point-service: getUltraSrtNcst
    end-point-service-key: Ld1kB90v%2BPy5LBEX2wWOXb6FLjdX44C1GY6VPuQN9M8xYU8w%2FeUBR7rJsApfXa10a1GTMFnJkdjRjFGyTQEvrg%3D%3D
  pid:
    file: ./keti-weather-collector.pid

info:
  app:
    name: keti-weather-collector
    version: 0.0.1-SNAPSHOT
    description: weather collector

---

spring:
  profiles:
    group:
      "local": "common,local"
      "vm": "common,vm"
      "dev": "common,dev"
      "prod": "common,prod"