spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.100.41:3306/keti?reconnect=true&characterEncoding=UTF-8
    username: keti
    password: 'qwer1234!@'
  kafka:
    producer:
      bootstrap-servers: 192.168.7.182:9092,192.168.7.183:9092,192.168.7.184:9092
      topic: dev-keti-weather
      acks: -1
      retries: 1
      batch-size: 16384
      linger-ms: 0
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
      buffer-memory: 33554432
      max-block-ms: 60000
      max-request-size: 125829120
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compresstion-type: lz4
      
logging:
  path:
    dir: /applog/keti-weather-collector
    file: keti-weather-collector
  level:
    root: info