spring:
  config:
    activate:
      on-profile: "common"
  main:
    web-application-type: none
  pid:
    file: ./keti-launcher-youtube.pid

info:
  app:
    name: keti-launcher-youtube
    version: 0.0.1-SNAPSHOT

---

spring:
  profiles:
    group:
      "local": "common,local"
      "vm": "common,vm"
      "dev": "common,dev"
      "prod": "common,prod"